language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: aefa103f3a05d243053dd9864fe9a66ad4dd8fe9
  local_dir: dist
  on:
    branch: master